export { default as HeroSection } from './hero-section'
export { default as AboutSection } from './about-section'
export { default as SkillsSection } from './skills-section'
export { default as BlogSection } from './blogs-section'
export { default as TestimonialSection } from './testimonials-section'
export { default as ServicesSection } from './services-section'
